function visualize_traj(robot, q, ax, save, prefix)
%VISUALIZE_TRAJ Visualize the trajectory generated by RRT
if nargin == 4
    prefix = '';
end
% Loop through the other positions
for i = 1:length(q)
    show(robot,q(i,:),"Parent",ax,"PreservePlot",false,"Collisions","on","Visuals","off");
    if save
        if i == length(q)
            saveas(ax,strcat('./Experiment/',string(prefix),sprintf('_%d_done.jpg',i)));
        else
            saveas(ax,strcat('./Experiment/',string(prefix),sprintf('_%d.jpg',i)));
        end
    end
    % Update the figure    
    drawnow
end

end

