function visualize_traj(robot, q, ax)
%VISUALIZE_TRAJ Visualize the trajectory generated by RRT

% Loop through the other positions
for i = 1:length(q)
    show(robot,q(i,:),"Parent",ax,"PreservePlot",false);
    
    % Update the figure    
    drawnow
end

end

